[tool.poetry]
name = "openweathermap-productizer-v1"
version = "1.0.0"
description = ""
authors = ["Digital Living International Ltd"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.80.0"
uvicorn = "^0.18.2"
aiohttp = "^3.8.1"
invoke = "^2.2.0"
orjson = "^3.7.12"
stringcase = "^1.2.0"
pydantic = {version = "^1.9.2", extras = ["dotenv"]}

[tool.poetry.dev-dependencies]

[tool.skjold]
report_only = false
sources = ["pyup", "gemnasium"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
