[tool.poetry]
name = "ioxio-dataspace-example-productizer"
version = "1.0.0"
description = ""
authors = ["IOXIO Oy"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.2"
uvicorn = "^0.27.1"
aiohttp = "^3.9.3"
invoke = "^2.2.0"
pydantic = "^2.6.1"

[tool.skjold]
report_only = false
sources = ["pyup", "gemnasium"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
